### ISSUE TITLE
certificate has exprired

### ISSUE THREAD

**Issue by DxrMorgan** [thomasnordquist/MQTT-Explorer#640] opened 2022-04-03 14:14 UTC
What idiotic situation with "certificate has expired" ??? Certificate is good and working. Another mqtt client work correct. Certificate not self signed. But remain 3 month to end. And app think certificate expired ???

**Comment by davidstx** [comment] 2022-06-19 10:31
Its the certificate in MQTT Explorer thats expired, you can download a certificate at this link
https://github.com/thomasnordquist/MQTT-Explorer/issues/596

**Comment by bj00rn** [comment] 2024-04-02 19:00
duplicate of #596

**Closed by bj00rn** 2024-04-02 19:00 UTC
