### ISSUE TITLE
Feature, graph of single json value

### ISSUE THREAD

**Issue by Laro88** [thomasnordquist/MQTT-Explorer#119] opened 2019-05-27 06:45 UTC
Hi Thomas.
I tried out your application with great success (seems rock solid) and the integrated charting of data is great for getting a glimpse into the state of the data.
One feature is hpoe to see (can't help you but testing) is to make a graph of values inside the objects when working with json. This would be great when IoT devices send objects back and forth that contains sensor data + more in one datagram.
Cheers

**Comment by thomasnordquist** [comment] 2019-05-27 21:12
I totally agree, this is a major feature.

The feature will be tracked here:
https://github.com/thomasnordquist/MQTT-Explorer/issues/77

I have a few ideas how to implement this, some of then easy and some of them hard to implement.
But it is THE most important feature I have planned.

**Comment by thomasnordquist** [comment] 2019-06-04 08:37
Closing since this is a duplicate of #77. This feature will come.

**Closed by thomasnordquist** 2019-06-04 08:37 UTC

**Comment by thomasnordquist** [comment] 2019-06-04 20:04
Coming soon, current status as of 9e15e2814743859775a77be5638d42c0ef6d295d
<img width="909" alt="Bildschirmfoto 2019-06-04 um 22 00 30" src="https://user-images.githubusercontent.com/7721625/58909944-9cb95c80-8714-11e9-88ad-fb46100441c7.png">

**Comment by thomasnordquist** [comment] 2019-07-22 14:20
Released with [v0.3.5](https://github.com/thomasnordquist/MQTT-Explorer/releases/tag/v0.3.5).
(Also a completely new panel has been added to display selected topics)
